# frozen_string_literal: true
source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'bcrypt', '~> 3.1', '>= 3.1.11'
gem 'dry-system', '~> 0.7.3'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'rack-parser', '~> 0.7.0'
gem 'roda', '~> 2.29'
gem 'roda-rest_api', '~> 2.0', '>= 2.0.1'
gem 'sequel', '~> 4.49'
gem 'sqlite3', '~> 1.3', '>= 1.3.13'
gem 'unicorn'
group :development, :test do
  gem 'faker', '~> 1.8', '>= 1.8.4'
  gem 'minitest', '~> 5.10', '>= 5.10.3'
  gem 'mocha', '~> 1.2', '>= 1.2.1'
end
# gem "rails"
